package com.tfg.rentalplatform.entity;

public enum NotificationType {
    RESERVATION_CREATED,
    RESERVATION_ACCEPTED,
    RESERVATION_REJECTED,
    RESERVATION_CANCELED,
    RESERVATION_COMPLETED,
    PAYMENT_CAPTURED,
    PAYMENT_REFUNDED,
    REVIEW_CREATED,
    MESSAGE_RECEIVED,
    ADMIN_ALERT
}
