spring.application.name=rental-platform-backend

server.port=8081
spring.profiles.active=dev

spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.validate-on-migrate=false

app.security.jwt.secret=${APP_JWT_SECRET:super-secret-key-change-in-production-please-1234567890}
app.security.jwt.expiration-minutes=${APP_JWT_EXP_MIN:120}
app.platform.fee-percent=${APP_PLATFORM_FEE_PERCENT:10}
